### ISSUE TITLE
Velocity-3.3.0 Start bug

### ISSUE THREAD

**Issue by fjess1** [RediCloud/cloud-v2#28]
INFO: Version: 2.1.0-SNAPSHOT
 INFO: Git: d2702d2a51c391054639a5faaddc4f6cf7bde1ad
 INFO: Branch: master
 INFO: CI-Build: 112

Error: https://haste.redicloud.dev/ahuraxejaw.sql

**Comment by paulkczw** [comment]
fixed [0817e53ab1bca6f594bfba23f880559d84125c73](https://github.com/RediCloud/cloud-v2/commit/0817e53ab1bca6f594bfba23f880559d84125c73)
