### ISSUE TITLE
Fehler beim erstellen eines FileTemplates

### ISSUE THREAD

**Issue by fjess1** [RediCloud/cloud-v2#33]
Als ich den Command "ft create default lobby" eingetragen habe, ist dieser Fehler hier erschienen:

https://haste.redicloud.dev/wavomesuda.yaml

**Comment by paulkczw** [comment]
fixed [1d70baa0eb](https://github.com/RediCloud/cloud-v2/commit/1d70baa0eb7c08a0924629c67c2822a2ff595e6a)
