### ISSUE TITLE
Duplicate Server Instances Starting 

### ISSUE THREAD

**Issue by abgxhoben** [RediCloud/cloud-v2#84]
### Console Error

![grafik](https://github.com/RediCloud/cloud-v2/assets/85188138/5f62c814-241b-4f2e-b872-75e38dc87a64)

### Bug Description

It has been observed that occasionally two instances of the same server start simultaneously. This issue is causing confusion as shown in the attached screenshot of Lobby-1.

![grafik](https://github.com/RediCloud/cloud-v2/assets/85188138/5f62c814-241b-4f2e-b872-75e38dc87a64)

### Steps to Reproduce

1. Start the server in the Lobby.
2. Observe the server list.
3. Notice that two instances of the same server appear.

### Expected Behavior

Only one instance of a server should start and appear in the lobby list. So one Lobby-1

### Software/Hardware

Java: 1.8, 21.0.3
Debaian 11 
Ram: 16GB

### Cloud-Version

Version: 2.3.6-SNAPSHOT
Git: e6a480abed4615cdb145d74e1e72ed747b398908
Branch: dev
CI-Build: 89

**Comment by paulkczw** [comment]
fixed with #[2f6abb4](https://github.com/RediCloud/cloud-v2/commit/95485216be2c153cedc056296d2c25992a0f0c41)
