### ISSUE TITLE
Global Ordner 

### ISSUE THREAD

**Issue by abgxhoben** [RediCloud/cloud-v2#88]
### Problem Description

Derzeit muss ich wenn ich ein Plugin habe welches auf jeden Server soll manuell in alle Ordner machen 

### Solution Description

Ich würde sagen das es ein Global Ordner gibt wenn ich da z.b in plugins Ordner 1 AntiCheat das geht dann auf jeden Server

**Comment by lisaaqt** [comment]
Moin @abgxhoben,

die einfachste Lösung dafür, wäre einfach ein FT (FileTemplate) zu erstellen und es jeder Gruppe einmal zuzuweisen. Somit kannst du dies dann einfach auf jedem Server haben.

Grüße,
Lisa
